### ISSUE TITLE
Standardize configuration to work anywhere!

### ISSUE THREAD

**Issue by Haaabeeel** [VPremiss/Crafty#12]
We have a problem!

Currently, relying on configurations internally cause not only issues with testing environments (where the app structure is like [Orchestra](https://packages.tools/testbench)'s or something), but also we also face abstraction issue where we do validations right after every call for `config()` to ensure working with a sane value!

The solution I'm working on is to implement configuration defaults and validations on the package service provider (any other package's really, since we're a helper package, yet including ourselves too), and then globalizing a `validated_config()` helper function to do exactly that.

What do you think? @GoodM4ven

**Comment by GoodM4ven** [comment]
We still have to input them twice, right? Maybe even more?
I'm not sure how it would look, but it seems to solve a current problem, like you mentioned.

-Give it a try?! ¯\_(ツ)_/¯

**Comment by Haaabeeel** [comment]
I mean commit [Arabicable#7](https://github.com/VPremiss/Arabicable/commit/874362751f731be85c8014f1023ab885bc309e48) wouldn't have been a breaking v2 if config was handled, yeah?

**Comment by Haaabeeel** [comment]
Done with!
