### ISSUE TITLE
Protected properties and methods cannot be used even on a container's service provider

### ISSUE THREAD

**Issue by GoodM4ven** [VPremiss/Crafty#25]
Yep, my fear was in place:
https://github.com/VPremiss/Arabicable/pull/18#issue-2261314744

**Comment by GoodM4ven** [comment]
I will see if I can access public methods (trait's) that already accessed the protected stuff!

**Comment by Haaabeeel** [comment]
@GoodM4ven THAT COULD be IT! (,,•o•,,)

**Comment by GoodM4ven** [comment]
Resolved with #26 .
